services:
  db:
    image: postgres:16-alpine
    container_name: courses_shop_db
    environment:
      POSTGRES_DB: courses_shop
      POSTGRES_USER: courses_shop
      POSTGRES_PASSWORD: courses_shop
    ports:
      - "5432:5432"
    volumes:
      - courses_shop_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U courses_shop -d courses_shop"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  courses_shop_postgres:
